=== sallethe/rss25SB/src/main/resources/rss25.tp1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://univ.fr/rss25" xmlns="http://univ.fr/rss25"
           elementFormDefault="qualified">
    
    <xs:element name="feed">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="rssTitle"/>
                <xs:element name="pubDate" type="xs:date"/>
                <xs:element name="copyright" type="rssTitle"/>
                <xs:element name="link" type="xs:anyURI"/>
                <xs:element name="item" maxOccurs="10">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="guid" type="xs:anyURI"/>
                            <xs:element name="title" type="rssTitle"/>
                            <xs:element name="category" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="term" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="published"/>
                            <xs:element name="image" minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute name="type" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="gif"/>
                                                <xs:enumeration value="jpeg"/>
                                                <xs:enumeration value="jpg"/>
                                                <xs:enumeration value="bmp"/>
                                                <xs:enumeration value="png"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="href" type="xs:anyURI" use="required"/>
                                    <xs:attribute name="alt" type="xs:string" use="required"/>
                                    <xs:attribute name="length" type="xs:int" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="content">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="rel" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="self"/>
                                                        <xs:enumeration value="alternate"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                            <xs:attribute name="type" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="text"/>
                                                        <xs:enumeration value="html"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                            <xs:attribute name="src" type="xs:anyURI" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="author"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="lang" type="xs:language" use="required"/>
            <xs:attribute name="version" type="xs:int" default="25"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="rssTitle">
        <xs:restriction base="xs:string">
            <xs:maxLength value="128"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="published" type="xs:date"/>
    <xs:element name="updated" substitutionGroup="published"/>
    
    <xs:element name="language">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[a-z]{2,3}(-([A-Z]{2}|[0-9]{3}))?" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
    
    <xs:element name="author">
        <xs:complexType>
            <xs:all>
                <xs:element name="name">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="64"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="email" minOccurs="0" type="xs:string"/>
                <!--xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="/\S*/"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element-->
                <xs:element name="uri" type="xs:anyURI" minOccurs="0"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="contributor" substitutionGroup="author"/>
</xs:schema>

=== sallethe/rss25SB/src/main/resources/test.xml
<?xml version="1.0" encoding="utf-8"?>

<rss:feed lang="fr" ver="25"
	xmlns:rss="http://univrouen.fr/rss25"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://univrouen.fr/rss25 rss25.tp1.xsd ">

	<rss:title>Physique : Toute l’actualité sur Le Monde.fr.</rss:title>
	<rss:pubDate>2025-02-26T11:11:08</rss:pubDate>
	<rss:copyright>Le Monde</rss:copyright>
	<rss:link rel="self" type="application/atom+xml" href="https://www.lemonde.fr/physique/rss_full.xml"/>
	<rss:item>
		<rss:guid>https://www.lemonde.fr/sciences/article/2025/02/21/ordinateurs-quantiques-microsoft-jette-un-pave-dans-la-mare_6557701_1650684.html</rss:guid>
		<rss:title>Ordinateurs quantiques : Microsoft dit être en mesure de les commercialiser d’ici à quelques années</rss:title>
		<rss:category term="Quantique"/>
		<rss:published>2025-02-21T17:00:25</rss:published>
		<rss:image alt="Image de l'ordinateur quantique" type="jpeg" href="https://img.lemde.fr/2025/02/20/167/0/2000/1000/644/322/60/0/b5f3402_sirius-fs-upload-1-gv03gmukptbh-1740046405354-majorana-1-002-4000px-1.jpg"/>
		<rss:content type="text">L’entreprise américaine a annoncé avoir fabriqué un matériau révolutionnaire, qui lui permettrait d’accélérer la réalisation d’un tel ordinateur, attendu dans quelques décennies dans ses précédentes prévisions.</rss:content>
		<rss:author>
			<rss:name>John Brecher</rss:name>
		</rss:author>
	</rss:item>
	<rss:item>
		<rss:guid>https://www.lemonde.fr/sciences/article/2025/02/18/la-maitrise-de-la-fusion-nucleaire-franchit-une-etape-avec-le-cea_6552914_1650684.html</rss:guid>
		<rss:title>Le CEA franchit une étape vers la maîtrise de la fusion nucléaire et dépasse la Chine</rss:title>
		<rss:category term="Nucléaire"/>
		<rss:updated>2025-02-19T11:38:16</rss:updated>
		<rss:content type="text">Sur son site des Bouches-du-Rhône, le Commissariat à l’énergie atomique est parvenu à maintenir un plasma plus de vingt-deux minutes à une température stationnaire de 50 millions de degrés Celsius. Un record réalisé grâce au tokamak WEST, qui détrône de cinq minutes celui obtenu par son rival, le tokamak chinois EAST, en janvier.</rss:content>
		<rss:author>
			<rss:name>LAURENCE GODART</rss:name>
			<rss:uri>https://www.cea.fr/</rss:uri>
		</rss:author>
	</rss:item>
	<rss:item>
		<rss:guid>https://www.lemonde.fr/sciences/article/2025/02/16/alain-aspect-prix-nobel-de-physique-l-echec-fait-partie-du-metier-le-decouragement-parfois-aussi_6548816_1650684.html</rss:guid>
		<rss:title>Alain Aspect, Prix Nobel de physique : « L’échec fait partie du métier, le découragement parfois aussi »</rss:title>
		<rss:category term="Quantique"/>
		<rss:published>2025-02-16T05:00:12</rss:published>
		<rss:image alt="Alain Aspect dans son bureau de Saclay" type="jpeg"	href="https://img.lemde.fr/2025/02/13/1574/0/4480/2240/644/322/60/0/8af84f5_sirius-fs-upload-1-26qwrjuatr1w-1739456765057-t6a0269.jpg"/>
		<rss:content type="text">« Je ne serais pas arrivé là si… » Chaque semaine, « Le Monde » interroge une personnalité sur un moment décisif de son existence. Le physicien revient aux sources de son amour de la physique expérimentale, puisé dans son village du Sud-Ouest.</rss:content>
		<rss:author>
			<rss:name>SIMONE PEROLARI</rss:name>
		</rss:author>
	</rss:item>
	<rss:item>
		<rss:guid>https://www.lemonde.fr/disparitions/article/2025/02/12/la-mort-d-yvonne-choquet-bruhat-pionniere-des-etudes-sur-les-ondes-gravitationnelles_6543990_3382.html</rss:guid>
		<rss:title>La mort d’Yvonne Choquet-Bruhat, pionnière des études sur les ondes gravitationnelles</rss:title>
		<rss:category term="Théorie"/>
		<rss:published>2025-02-12T19:11:59</rss:published>
		<rss:image alt="La mathématicienne et physicienne française Yvonne Choquet-Bruhat pose après avoir été	élue membre de l’Académie des sciences, à Antony (Hauts-de-Seine), le 14 mai 1979."
				type="jpeg" href="https://img.lemde.fr/2025/02/12/468/0/5616/2808/644/322/60/0/e856844_sirius-fs-upload-1-rkx2bwibz96c-1739382196893-000-8xu83w.jpg"/>
		<rss:content type="text">L’importance des travaux de la scientifique française, aux confins des mathématiques et de la physique théorique, lui avait valu d’être la première femme élue à l’Académie des sciences. Elle est morte le 11 février, à 101 ans.</rss:content>
		<rss:author>
			<rss:name>JOEL ROBINE</rss:name>
			<rss:email>joel;robine@afp.fr</rss:email>
		</rss:author>
	</rss:item>
	<rss:item>
		<rss:guid>https://www.lemonde.fr/sciences/article/2025/02/12/ampere-genial-touche-a-tout-et-stereotype-du-savant-distrait_6543438_1650684.html</rss:guid>
		<rss:title>Ampère, génial touche-à-tout et stéréotype du savant distrait</rss:title>
		<rss:category term="Historique"/>
		<rss:updated>2025-02-13T09:42:16</rss:updated>
		<rss:content type="text">Dans sa carte blanche au « Monde », Etienne Ghys rend hommage au scientifique auteur de multiples découvertes, dont on célèbre cette année le 250ᵉ anniversaire de la naissance.</rss:content>
		<rss:author>
			<rss:name >Chez Gertrud</rss:name>
		</rss:author>
	</rss:item>
	<rss:item>
		<rss:guid>https://www.lemonde.fr/sciences/article/2025/01/10/un-robot-flottant-pour-ecumer-les-microplastiques_6491123_1650684.html</rss:guid>
		<rss:title>Un robot flottant pour écumer les microplastiques</rss:title>
		<rss:category term="Robotique"/>
		<rss:published>2025-01-10T10:00:11</rss:published>
		<rss:content type="text">Après avoir travaillé sur la récupération de pétrole dans l’eau, une équipe coréenne a adapté son outil pour aspirer les billes de plastique présentes en surface.</rss:content>
		<rss:contributor>
			<rss:name>CHEZ Gertrud</rss:name>
		</rss:contributor>
	</rss:item>
</rss:feed>
